# Generated by Django 5.0.6 on 2024-09-14 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address_place', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
