# Generated by Django 5.0.6 on 2024-08-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_address_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
