# Generated by Django 5.0.6 on 2024-08-30 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_care_of_user_age_user_city_user_district_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Care_of',
            new_name='care_of',
        ),
    ]
