# Generated by Django 5.0.6 on 2024-08-16 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicinestoretransactionhistory',
            old_name='medicine_manufacturer',
            new_name='medicine_manufacture',
        ),
        migrations.AddField(
            model_name='medicinestoretransactionhistory',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
