# Generated by Django 5.0.6 on 2024-08-14 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicinestoretransactionhistory',
            old_name='qty',
            new_name='add_qty',
        ),
        migrations.AddField(
            model_name='medicinestoretransactionhistory',
            name='available_qty',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='medicinestoretransactionhistory',
            name='minus_qty',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='medicinestoretransactionhistory',
            name='sell_qty',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='medicinestoretransactionhistory',
            name='transfer_qty',
            field=models.IntegerField(null=True),
        ),
    ]
