# Generated by Django 5.0.6 on 2024-08-14 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_qty_medicinestoretransactionhistory_add_qty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinestoretransactionhistory',
            name='add_qty',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='medicinestoretransactionhistory',
            name='minus_qty',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='medicinestoretransactionhistory',
            name='transfer_qty',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
