# Generated by Django 5.0.6 on 2024-08-14 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_medicinestoretransactionhistory_add_qty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinestoretransactionhistory',
            name='medicine_manufacturer',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='medicinestoretransactionhistory',
            name='medicine_name',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
