# Generated by Django 5.0.6 on 2024-07-25 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0002_remove_medicine_medicine_qty'),
        ('store', '0003_remove_mainstoremedicinetransaction_medicine_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainToMiniStoreMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('from_store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='from_store', to='store.store')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='medicine.medicine')),
                ('to_store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='to_store', to='store.store')),
            ],
            options={
                'db_table': 'main_to_mini_store_medicine',
            },
        ),
    ]
