# Generated by Django 5.0.6 on 2024-07-25 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0002_remove_medicine_medicine_qty'),
        ('store', '0004_maintoministoremedicine'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainToMiniStoreMedicineTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=500, null=True)),
                ('qty', models.IntegerField(null=True)),
                ('medicine_manufacturer', models.CharField(max_length=500, null=True)),
                ('medicine_expiry', models.DateField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('from_store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='main_to_mini_transaction_from_store', to='store.store')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='medicine.medicine')),
                ('to_store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='main_to_mini_transaction_to_store', to='store.store')),
            ],
            options={
                'db_table': 'main_to_mini_store_medicine_transaction',
            },
        ),
    ]
