# Generated by Django 5.0.6 on 2024-08-14 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_medicinestoretransactionhistory_medicine_manufacturer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicinestoretransactionhistory',
            name='sell_qty',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
