# Generated by Django 5.0.6 on 2024-09-15 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('previous_treatment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='previoustreatment',
            table='previous_treatment',
        ),
    ]
