# Generated by Django 5.0.6 on 2024-08-18 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientbilldetail',
            name='patient_bill',
        ),
        migrations.RemoveField(
            model_name='patientbilldetail',
            name='medicine',
        ),
        migrations.DeleteModel(
            name='PatientBill',
        ),
        migrations.DeleteModel(
            name='PatientBillDetail',
        ),
    ]
