# Generated by Django 5.0.6 on 2024-08-18 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bill', '0002_remove_patientbilldetail_patient_bill_and_more'),
        ('medicine', '0003_rename_manufacturer_mobile_medicine_mobile'),
        ('patient', '0001_initial'),
        ('store', '0002_rename_medicine_manufacturer_medicinestoretransactionhistory_medicine_manufacture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100, null=True)),
                ('sgst', models.IntegerField(blank=True, default=0, null=True)),
                ('cgst', models.IntegerField(blank=True, default=0, null=True)),
                ('credit', models.IntegerField(blank=True, default=0, null=True)),
                ('cash', models.IntegerField(blank=True, default=0, null=True)),
                ('online', models.IntegerField(blank=True, default=0, null=True)),
                ('shipping_packing', models.IntegerField(blank=True, default=0, null=True)),
                ('discount', models.IntegerField(blank=True, default=0, null=True)),
                ('total', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='patient.patient')),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='store.store')),
            ],
            options={
                'db_table': 'patient_bill',
            },
        ),
        migrations.CreateModel(
            name='PatientBillDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_qty', models.IntegerField(default=0, null=True)),
                ('sell_qty', models.IntegerField(default=0, null=True)),
                ('mrp', models.IntegerField(default=0, null=True)),
                ('discount', models.IntegerField(default=0, null=True)),
                ('sale_rate', models.IntegerField(default=0, null=True)),
                ('hsn', models.IntegerField(default=0, null=True)),
                ('gst', models.IntegerField(default=0, null=True)),
                ('amount', models.IntegerField(default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('medicine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine.medicine')),
                ('patient_bill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bill.patientbill')),
            ],
            options={
                'db_table': 'patient_bill_detail',
            },
        ),
    ]
