# Generated by Django 5.0.6 on 2024-08-18 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CGST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cgst_percent', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'cgst',
            },
        ),
        migrations.CreateModel(
            name='SGST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sgst_percent', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'sgst',
            },
        ),
    ]
