# Generated by Django 5.0.6 on 2024-08-07 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0001_initial'),
        ('patient', '0005_remove_patient_patient_bp_max_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentWard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('price', models.IntegerField(null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hospital_Appointment_visit',
            },
        ),
        migrations.CreateModel(
            name='PatientAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_diseases', models.TextField(blank=True, null=True)),
                ('patient_bp_min', models.IntegerField(blank=True, null=True)),
                ('patient_bp_max', models.IntegerField(blank=True, null=True)),
                ('patient_weight', models.IntegerField(blank=True, null=True)),
                ('pulses', models.IntegerField(blank=True, default=72, null=True)),
                ('fees', models.IntegerField(blank=True, default=0, null=True)),
                ('paid', models.CharField(blank=True, max_length=10, null=True)),
                ('remaining', models.IntegerField(blank=True, default=0, null=True)),
                ('cash', models.IntegerField(blank=True, default=0, null=True)),
                ('online', models.IntegerField(blank=True, default=0, null=True)),
                ('appointment_date', models.DateField(blank=True, default=None, null=True)),
                ('appointment_time', models.TimeField(blank=True, default=None, null=True)),
                ('appoint_status', models.CharField(default='unchecked', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('appoint_ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.appointmentward')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
            options={
                'db_table': 'patient_appointment',
            },
        ),
    ]
