# Generated by Django 5.0.6 on 2024-08-07 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientappointment',
            name='pulses',
        ),
    ]
