# Generated by Django 5.0.6 on 2024-08-30 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientappointment',
            old_name='patient_bp_max',
            new_name='Respiration',
        ),
        migrations.RenameField(
            model_name='patientappointment',
            old_name='patient_bp_min',
            new_name='oxygen',
        ),
        migrations.AddField(
            model_name='patientappointment',
            name='patient_bp',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientappointment',
            name='pulse',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientappointment',
            name='temperature',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
