# Generated by Django 5.0.6 on 2024-08-30 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_rename_patient_bp_max_patientappointment_respiration_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientappointment',
            old_name='paid',
            new_name='pay_amount',
        ),
        migrations.AddField(
            model_name='patientappointment',
            name='discount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='patientappointment',
            name='extra_fees',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
