# Generated by Django 5.0.6 on 2024-08-30 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0004_rename_paid_patientappointment_pay_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientappointment',
            name='patient_bp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
