# Generated by Django 5.0.6 on 2024-08-30 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0005_alter_patientappointment_patient_bp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientappointment',
            old_name='Respiration',
            new_name='respiration',
        ),
    ]
