# Generated by Django 5.0.6 on 2024-09-23 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0003_patientappointmentdiagnosis_created_at_and_more'),
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineOrderHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.IntegerField(default=0, null=True)),
                ('discount', models.IntegerField(default=0, null=True)),
                ('shipping', models.IntegerField(default=0, null=True)),
                ('pay_amount', models.IntegerField(default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor')),
            ],
            options={
                'db_table': 'medicine_order_head',
            },
        ),
        migrations.CreateModel(
            name='MedicineOrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_qty', models.IntegerField(default=0, null=True)),
                ('mrp', models.IntegerField(default=0, null=True)),
                ('amount', models.IntegerField(default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('medicine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine.medicine')),
                ('head', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_order.medicineorderhead')),
            ],
            options={
                'db_table': 'medicine_order_detail',
            },
        ),
    ]
