# Generated by Django 5.0.6 on 2024-09-23 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicineorderhead',
            name='pay_amount',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='medicineorderhead',
            name='shipping',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='medicineorderhead',
            name='subtotal',
            field=models.FloatField(default=0, null=True),
        ),
    ]
