# Generated by Django 5.0.6 on 2024-10-26 06:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_patientappointmentdiagnosis_created_at_and_more'),
        ('medicine', '0004_medicine_video_link'),
        ('my_order', '0003_alter_medicineorderdetail_amount_and_more'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineOrderBillHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100, null=True)),
                ('subtotal', models.FloatField(default=0, null=True)),
                ('discount', models.IntegerField(default=0, null=True)),
                ('shipping', models.FloatField(default=0, null=True)),
                ('pay_amount', models.FloatField(default=0, null=True)),
                ('sgst', models.IntegerField(blank=True, default=0, null=True)),
                ('cgst', models.IntegerField(blank=True, default=0, null=True)),
                ('credit', models.IntegerField(blank=True, default=0, null=True)),
                ('cash', models.IntegerField(blank=True, default=0, null=True)),
                ('online', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor')),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.store')),
            ],
            options={
                'db_table': 'medicine_order_bill_head',
            },
        ),
        migrations.CreateModel(
            name='MedicineOrderBillDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_qty', models.IntegerField(default=0, null=True)),
                ('order_qty', models.IntegerField(default=0, null=True)),
                ('sell_qty', models.IntegerField(default=0, null=True)),
                ('mrp', models.FloatField(default=0, null=True)),
                ('sale_rate', models.IntegerField(default=0, null=True)),
                ('discount', models.IntegerField(default=0, null=True)),
                ('amount', models.FloatField(default=0, null=True)),
                ('hsn', models.IntegerField(default=0, null=True)),
                ('gst', models.IntegerField(default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('medicine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine.medicine')),
                ('head', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_order.medicineorderbillhead')),
            ],
            options={
                'db_table': 'medicine_order_bill_detail',
            },
        ),
    ]
