# Generated by Django 5.0.6 on 2024-10-26 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_order', '0004_medicineorderbillhead_medicineorderbilldetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicineorderbillhead',
            name='cash',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='medicineorderbillhead',
            name='cgst',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='medicineorderbillhead',
            name='credit',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='medicineorderbillhead',
            name='online',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='medicineorderbillhead',
            name='sgst',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
