# Generated by Django 5.0.6 on 2024-10-27 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_order', '0007_medicineorderhead_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineorderbilldetail',
            name='tax',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='medicineorderbilldetail',
            name='taxable_amount',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='medicineorderdetail',
            name='gst',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='medicineorderdetail',
            name='hsn',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='medicineorderdetail',
            name='tax',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='medicineorderdetail',
            name='taxable_amount',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='medicineorderbilldetail',
            name='gst',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='medicineorderbilldetail',
            name='hsn',
            field=models.FloatField(default=0, null=True),
        ),
    ]
