# Generated by Django 5.0.6 on 2024-10-27 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_order', '0008_medicineorderbilldetail_tax_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineorderbillhead',
            name='old_credit',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
