# Generated by Django 5.0.6 on 2024-10-27 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_order', '0009_medicineorderbillhead_old_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineorderbillhead',
            name='order_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
