# Generated by Django 5.0.6 on 2024-10-27 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_order', '0010_medicineorderbillhead_order_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicineorderbillhead',
            name='order_type',
            field=models.IntegerField(default=1, help_text='1=In state,2=other state,3=bill of supply'),
            preserve_default=False,
        ),
    ]
