# Generated by Django 5.0.6 on 2024-10-28 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_order', '0011_alter_medicineorderbillhead_order_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicineorderbilldetail',
            name='sale_rate',
            field=models.FloatField(default=0, null=True),
        ),
    ]
