# Generated by Django 5.0.6 on 2024-10-28 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_order', '0012_alter_medicineorderbilldetail_sale_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicineorderbilldetail',
            name='gst',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
