# Generated by Django 5.0.6 on 2024-10-31 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_order', '0015_estimatemedicineorderbillhead_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineorderdetail',
            name='invoice_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
