# Generated by Django 5.0.6 on 2024-10-31 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_order', '0016_medicineorderdetail_invoice_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicineorderdetail',
            name='invoice_number',
        ),
        migrations.AddField(
            model_name='medicineorderhead',
            name='invoice_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
