# Generated by Django 5.0.6 on 2024-11-01 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_order', '0018_estimatemedicineorderbillhead_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimatemedicineorderbillhead',
            name='account_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='estimatemedicineorderbillhead',
            name='bar_code',
            field=models.ImageField(blank=True, null=True, upload_to='bank_account_barcode'),
        ),
        migrations.AddField(
            model_name='estimatemedicineorderbillhead',
            name='ifc_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='estimatemedicineorderbillhead',
            name='upi_id_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicineorderbillhead',
            name='account_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicineorderbillhead',
            name='bar_code',
            field=models.ImageField(blank=True, null=True, upload_to='bank_account_barcode'),
        ),
        migrations.AddField(
            model_name='medicineorderbillhead',
            name='ifc_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicineorderbillhead',
            name='upi_id_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
