# Generated by Django 5.0.6 on 2024-11-03 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_order', '0019_estimatemedicineorderbillhead_account_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicineorderbillhead',
            old_name='credit',
            new_name='current',
        ),
    ]
