# Generated by Django 5.0.6 on 2024-11-04 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_order', '0020_rename_credit_medicineorderbillhead_current'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estimatemedicineorderbillhead',
            old_name='credit',
            new_name='current',
        ),
    ]
