# Generated by Django 5.0.6 on 2024-11-16 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_order', '0021_rename_credit_estimatemedicineorderbillhead_current'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineorderbillhead',
            name='estimate_status',
            field=models.IntegerField(default=0, help_text='0=pending,1=complete'),
        ),
    ]
