# Generated by Django 5.0.6 on 2024-11-18 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_order', '0023_medicineorderbillhead_total_without_previous_bill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicineorderbillhead',
            name='total_without_previous_bill',
        ),
    ]
