# Generated by Django 5.0.6 on 2024-11-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_order', '0024_remove_medicineorderbillhead_total_without_previous_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineorderbillhead',
            name='total_without_previous_bill',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
