# Generated by Django 5.0.6 on 2024-11-19 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_order', '0025_medicineorderbillhead_total_without_previous_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimatemedicineorderbilldetail',
            name='gst',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='estimatemedicineorderbilldetail',
            name='hsn',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='medicineorderbilldetail',
            name='gst',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='medicineorderbilldetail',
            name='hsn',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='medicineorderdetail',
            name='gst',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='medicineorderdetail',
            name='hsn',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
