# Generated by Django 5.0.6 on 2024-11-28 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_order', '0026_alter_estimatemedicineorderbilldetail_gst_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimatemedicineorderbillhead',
            name='total_without_previous_bill',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
