# Generated by Django 5.0.6 on 2024-11-29 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_order', '0027_estimatemedicineorderbillhead_total_without_previous_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimatemedicineorderbillhead',
            name='new_credit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
