# Generated by Django 5.0.6 on 2024-11-29 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_order', '0028_estimatemedicineorderbillhead_new_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineorderbillhead',
            name='new_credit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
