# Generated by Django 5.0.6 on 2024-11-30 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_order', '0030_estimatemedicineorderbillhead_discount_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineorderbillhead',
            name='amount_remark',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicineorderbillhead',
            name='extra_cash_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='medicineorderbillhead',
            name='extra_online_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
