# Generated by Django 5.0.6 on 2024-12-09 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_order', '0032_estimatemedicineorderbillhead_amount_remark_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('sequence', models.IntegerField(default=0)),
            ],
        ),
    ]
