# Generated by Django 5.0.6 on 2024-12-09 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_order', '0033_invoicetracker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoicetracker',
            old_name='sequence',
            new_name='last_invoice_number',
        ),
    ]
