# Generated by Django 5.0.6 on 2024-12-15 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_patientappointmentdiagnosis_created_at_and_more'),
        ('medicine', '0007_medicine_gst_medicine_hsn'),
        ('my_order', '0034_rename_sequence_invoicetracker_last_invoice_number'),
        ('store', '0003_medicinestore_min_medicine_record_qty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineUnregisteredOrderBillDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_qty', models.IntegerField(default=0, null=True)),
                ('order_qty', models.IntegerField(default=0, null=True)),
                ('sell_qty', models.IntegerField(default=0, null=True)),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('discount', models.IntegerField(default=0, null=True)),
                ('sale_rate', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('hsn', models.CharField(blank=True, max_length=10, null=True)),
                ('gst', models.IntegerField(blank=True, default=0, null=True)),
                ('taxable_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('tax', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('head', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_order.medicineorderbillhead')),
                ('medicine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine.medicine')),
            ],
            options={
                'db_table': 'medicine_unregistered_order_bill_detail',
            },
        ),
        migrations.CreateModel(
            name='MedicineUnregisteredOrderBillHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('discount', models.IntegerField(default=0, null=True)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('shipping', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('pay_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('total_without_previous_bill', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('sgst', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cgst', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('old_credit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('new_credit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('current', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cash', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('online', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('extra_cash_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('extra_online_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amount_remark', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.IntegerField(help_text='0=pending,1=inprocess,2=packing,3=dispatch,4=out of delivery,5=delivered')),
                ('estimate_status', models.IntegerField(default=0, help_text='0=pending,1=complete')),
                ('order_type', models.IntegerField(help_text='1=In state,2=other state,3=bill of supply')),
                ('account_number', models.CharField(blank=True, max_length=100, null=True)),
                ('ifc_number', models.CharField(blank=True, max_length=100, null=True)),
                ('upi_id_number', models.CharField(blank=True, max_length=100, null=True)),
                ('bar_code', models.ImageField(blank=True, null=True, upload_to='bank_account_barcode')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor')),
                ('order_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='my_order.medicineorderhead')),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.store')),
            ],
            options={
                'db_table': 'medicine_unregistered_order_bill_head',
            },
        ),
    ]
