# Generated by Django 5.0.6 on 2024-12-15 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_order', '0036_alter_medicineunregisteredorderbilldetail_head_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineunregisteredorderbillhead',
            name='head',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='UnregisteredOrderBillHead', to='my_order.medicineorderbillhead'),
        ),
    ]
