# Generated by Django 5.0.6 on 2024-12-15 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_order', '0037_medicineunregisteredorderbillhead_head'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicineunregisteredorderbillhead',
            name='head',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='headUnregisteredOrderBillHead', to='my_order.medicineorderbillhead'),
        ),
        migrations.AlterField(
            model_name='medicineunregisteredorderbillhead',
            name='order_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_idUnregisteredOrderBillHead', to='my_order.medicineorderhead'),
        ),
    ]
