# Generated by Django 5.0.6 on 2024-12-16 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_order', '0038_alter_medicineunregisteredorderbillhead_head_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineorderbillhead',
            name='final_bill_status',
            field=models.IntegerField(default=0, help_text='0=pending,1=complete'),
        ),
    ]
