# Generated by Django 5.0.6 on 2024-12-21 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_order', '0039_medicineorderbillhead_final_bill_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimatemedicineorderbillhead',
            name='state_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='medicineorderbillhead',
            name='state_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='medicineunregisteredorderbillhead',
            name='state_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
