# Generated by Django 5.0.6 on 2025-01-09 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_order', '0040_estimatemedicineorderbillhead_state_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstimateInvoiceTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('last_invoice_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='NormalInvoiceTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('last_invoice_number', models.IntegerField(default=0)),
            ],
        ),
    ]
