# Generated by Django 5.0.6 on 2025-03-06 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_order', '0041_estimateinvoicetracker_normalinvoicetracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicineorderbillhead',
            name='delivery_status_id',
            field=models.IntegerField(blank=True, help_text='1=pending,2=dispatched,3=delivered', null=True),
        ),
        migrations.AddField(
            model_name='medicineorderbillhead',
            name='track_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
