# Generated by Django 5.0.6 on 2025-03-25 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_order', '0043_directestimatehead_directestimatedetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='directestimatedetail',
            name='batch_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='estimatemedicineorderbilldetail',
            name='batch_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='medicineorderbilldetail',
            name='batch_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='medicineunregisteredorderbilldetail',
            name='batch_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
