# Generated by Django 5.0.6 on 2025-03-30 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_order', '0044_directestimatedetail_batch_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectEstimateInvoiceTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('last_invoice_number', models.IntegerField(default=0)),
            ],
        ),
    ]
