# Generated by Django 5.1.7 on 2025-04-20 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '0006_patientestimatemedicinebillhead_flat_discount_and_more'),
        ('store', '0003_medicinestore_min_medicine_record_qty_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'procedure',
            },
        ),
        migrations.CreateModel(
            name='ProcedureBillDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('discount', models.IntegerField(default=0, null=True)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('flat_discount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('pay_amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('total_without_previous_bill', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('old_credit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('new_credit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cash', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('online', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('extra_cash_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('extra_online_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amount_remark', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.IntegerField(help_text='0=pending,1=inprocess,2=packing,3=dispatch,4=out of delivery,5=delivered')),
                ('account_number', models.CharField(blank=True, max_length=100, null=True)),
                ('ifc_number', models.CharField(blank=True, max_length=100, null=True)),
                ('upi_id_number', models.CharField(blank=True, max_length=100, null=True)),
                ('bar_code', models.ImageField(blank=True, null=True, upload_to='bank_account_barcode')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
                ('procedure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='procedure.procedure')),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.store')),
            ],
            options={
                'db_table': 'procedure_bill_head',
            },
        ),
    ]
