# Generated by Django 5.1.7 on 2025-04-20 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0002_categoryprocedure_procedure_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='procedure.categoryprocedure'),
        ),
    ]
