# Generated by Django 5.1.7 on 2025-04-20 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_patientestimatemedicinebillhead_flat_discount_and_more'),
        ('procedure', '0003_alter_procedure_category'),
        ('store', '0003_medicinestore_min_medicine_record_qty_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProcedureBillDetail',
            new_name='ProcedureBillHead',
        ),
    ]
