# Generated by Django 5.1.7 on 2025-04-22 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0004_rename_procedurebilldetail_procedurebillhead'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedurebillhead',
            name='procedure',
        ),
        migrations.CreateModel(
            name='ProcedureBillDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('sell_qty', models.IntegerField(default=0, null=True)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('from_date', models.DateTimeField(blank=True, null=True)),
                ('to_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('head', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='procedure.procedurebillhead')),
                ('procedure', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='procedure.procedure')),
            ],
            options={
                'db_table': 'procedure_bill_detail',
            },
        ),
    ]
