# Generated by Django 5.1.7 on 2025-04-22 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procedure', '0005_remove_procedurebillhead_procedure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedurebillhead',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
