# Generated by Django 5.0.6 on 2024-08-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_diseases',
            field=models.TextField(blank=True, null=True),
        ),
    ]
