# Generated by Django 5.0.6 on 2025-02-18 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_patientestimatemedicinebillhead_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientestimatemedicinebillhead',
            name='head',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.patientmedicinebillhead'),
        ),
    ]
