# Generated by Django 5.0.6 on 2024-08-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_patient_patient_diseases'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='patient_bp',
            new_name='patient_bp_max',
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_bp_min',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
