# Generated by Django 5.0.6 on 2024-08-27 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_patient_other_reference_patient_social_media_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='patient_age',
        ),
    ]
