# Generated by Django 5.0.6 on 2025-02-22 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_patientestimatemedicinebillhead_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientmedicineunregisteredbillhead',
            name='final_bill_status',
            field=models.IntegerField(default=0, help_text='0=pending,1=complete'),
        ),
    ]
