# Generated by Django 5.0.6 on 2024-08-04 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_rename_patient_bp_patient_patient_bp_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
