# Generated by Django 5.0.6 on 2024-08-07 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_patient_patient_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='patient_bp_max',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='patient_bp_min',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='patient_diseases',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='patient_weight',
        ),
    ]
