# Generated by Django 5.0.6 on 2025-03-29 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_patientmedicineunregisteredbillhead_final_bill_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientestimatemedicinebilldetail',
            name='batch_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patientmedicinebilldetail',
            name='batch_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patientmedicineunregisteredbilldetail',
            name='batch_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
