# Generated by Django 5.1.7 on 2025-04-20 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_patientestimatemedicinebilldetail_batch_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientestimatemedicinebillhead',
            name='flat_discount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='patientmedicinebillhead',
            name='flat_discount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='patientmedicineunregisteredbillhead',
            name='flat_discount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
