# Generated by Django 5.1.7 on 2025-06-01 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_patientestimatemedicinebillhead_flat_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='alcohol',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='smoking',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='tobacco',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
