# Generated by Django 5.0.6 on 2024-08-16 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='manufacturer',
            new_name='manufacture',
        ),
    ]
