# Generated by Django 5.0.6 on 2024-08-09 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='medicine_price',
            field=models.IntegerField(null=True),
        ),
    ]
