# Generated by Django 5.0.6 on 2024-08-16 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0002_rename_manufacturer_medicine_manufacture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='manufacturer_mobile',
            new_name='mobile',
        ),
    ]
