# Generated by Django 5.0.6 on 2024-09-24 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0002_medicine_desc_medicine_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
