# Generated by Django 5.0.6 on 2024-08-14 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0002_medicine_medicine_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
