# Generated by Django 5.0.6 on 2024-09-24 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0003_medicine_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='video_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
