# Generated by Django 5.0.6 on 2024-11-01 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0004_medicine_video_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='recom_to_doctor',
            field=models.BooleanField(default=True),
        ),
    ]
