# Generated by Django 5.0.6 on 2024-11-19 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0006_alter_medicine_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='gst',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='medicine',
            name='hsn',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
