# Generated by Django 5.1.7 on 2025-04-04 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menupurpose_menucategory_menu_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucategory',
            name='cat_color',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
