# Generated by Django 5.0.6 on 2024-09-15 03:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diagnosis', '0001_initial'),
        ('disease', '0001_initial'),
        ('medicine', '0001_initial'),
        ('patient', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialist', models.CharField(max_length=100, null=True)),
                ('degree', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'doctor',
            },
        ),
        migrations.CreateModel(
            name='PatientAppointmentHead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_r', models.CharField(blank=True, max_length=100, null=True)),
                ('procto', models.CharField(blank=True, max_length=100, null=True)),
                ('probing', models.CharField(blank=True, max_length=100, null=True)),
                ('o_e', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.doctor')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
            options={
                'db_table': 'patient_appointment_head',
            },
        ),
        migrations.CreateModel(
            name='PatientAppointmentDiagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='diagnosis.diagnosisdiseasename')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='diagnosis.diagnosisposition')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='diagnosis.diagnosistype')),
                ('head', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.patientappointmenthead')),
            ],
            options={
                'db_table': 'patient_appointment_diagnosis',
            },
        ),
        migrations.CreateModel(
            name='OtherAssociatesComplaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaints', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('bleeding', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='disease.bleeding')),
                ('severity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='disease.severity')),
                ('since', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='disease.since')),
                ('head', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.patientappointmenthead')),
            ],
            options={
                'db_table': 'other_associates_complaints',
            },
        ),
        migrations.CreateModel(
            name='ChiefComplaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaints', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('bleeding', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='disease.bleeding')),
                ('severity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='disease.severity')),
                ('since', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='disease.since')),
                ('head', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.patientappointmenthead')),
            ],
            options={
                'db_table': 'chief_complaints',
            },
        ),
        migrations.CreateModel(
            name='PatientAppointmentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='patient_appointment_image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('head', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.patientappointmenthead')),
            ],
            options={
                'db_table': 'patient_appointment_image',
            },
        ),
        migrations.CreateModel(
            name='PatientMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('head', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.patientappointmenthead')),
                ('medicine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='medicine.medicine')),
            ],
            options={
                'db_table': 'patient_medicine',
            },
        ),
    ]
