# Generated by Django 5.0.6 on 2024-08-14 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
        ('medicine', '0003_medicine_type'),
        ('patient', '0005_remove_patient_patient_bp_max_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientAppointmentChecked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_diseases', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='doctor.doctor')),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='patient.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PatientAppointmentCheckedDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('head_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='doctor.patientappointmentchecked')),
                ('medicine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='medicine.medicine')),
            ],
        ),
    ]
