# Generated by Django 5.0.6 on 2024-09-15 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bleeding',
            old_name='time',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='severity',
            old_name='time',
            new_name='type',
        ),
    ]
