# Generated by Django 5.0.6 on 2024-09-15 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnosistype',
            old_name='name',
            new_name='type',
        ),
        migrations.AddField(
            model_name='diagnosisposition',
            name='position',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='diagnosistype',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diagnosis.diagnosisposition'),
        ),
        migrations.AlterField(
            model_name='diagnosisposition',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diagnosis.diagnosisdiseasename'),
        ),
    ]
